export const Permission = Object.freeze({
  CREATE_VOTING: 'CREATE_VOTING',
  EDIT_VOTING: 'EDIT_VOTING',
  VIEW_ALL_VOTINGS: 'VIEW_ALL_VOTINGS',
  VIEW_ASSIGNED_VOTINGS: 'VIEW_ASSIGNED_VOTINGS',
  CAST_VOTE: 'CAST_VOTE',
  GENERATE_REPORTS: 'GENERATE_REPORTS',
});